from compiler.errors import SyntaxError 

class Parser:
    def __init__(self, tokens):
        # This is the Parser class responsible for analyzing the syntax of the program
        # It takes the tokens generated by the lexer and builds an abstract syntax tree (AST)
        # The parser implements a recursive descent parsing technique for the Minecraft-themed language ensuring
        # that everything is readable, and modular and it is a simple technique to implement for parsers
        
        self.tokens = tokens  # List of tokens from the lexer
        self.pos = 0  # Current position in the token list
        self.current_token = self.tokens[0] if tokens else None  # Current token being processed by the parser
        self.ast = []  # This will store our abstract syntax tree
    def parse(self):
        # Starts the recursive descent parsing process
        self.program()
        return self.ast 
    
    def program(self):
        # Parses the complete program and its sequence of statements
        # Continues parsing statements until the end of input is reached
        while not self._at_end() and not self._match('DELIMITER', '}'):
            self.statement()

    def statement(self):
        # Parses a single statement in the program
        # Statements can be declarations (craft), if statements (mine), or loops (dig)
        # Each keyword represents a different type of statement in our Minecraft language
        
        if self._match('CRAFT'):
            self.declaration()
        elif self._match('MINE'):
            self.if_statement()
        elif self._match('DIG'):
            self.loop()
        else:
            # If none of the expected statement keywords is found, a syntax error is raised
            # as part of the error handling mechanism of the compiler
            raise self._error("Unexpected statement. Expected 'craft', 'mine', or 'dig'")
        

    def declaration(self):
        # Parses a variable declaration statement  such as craft x = value;
        
        self._consume('CRAFT') 
        identifier = self._consume('IDENTIFIER', message="Expected variable name after 'craft'")
        self._consume('OPERATOR', '=', "Missing '=' in declaration")
        expression = self.expression()
        self._consume('DELIMITER', ';', "Missing ';' after declaration")

        self.ast.append({
            'type': 'declaration',
            'identifier': identifier['value'],
            'expression': expression
        })

    def if_statement(self):
        # Parses an if statement which uses the keywords mine, and the else_block for the if else common syntax, for example (mine (condition) { ... } else_block { ... })
        
        self._consume('MINE')
        self._consume('DELIMITER', '(')
        condition = self.condition() 
        self._consume('DELIMITER', ')')
        self._consume('DELIMITER', '{')
        ast_before = len(self.ast)

        self.program()
        true_block = self.ast[ast_before:]
        self.ast = self.ast[:ast_before]


        self._consume('DELIMITER', '}')

        if_stmt = {
            'type': 'if_statement',
            'condition': condition,
            'true_block': true_block
        }
        
        # Check if there's an else clause (else_block) present in the conditional
        if self._match('ELSE_BLOCK'):
            self._consume('ELSE_BLOCK')
            self._consume('DELIMITER', '{') 


            ast_before = len(self.ast)
            self.program()
            false_block = self.ast[ast_before:]
            self.ast = self.ast[:ast_before]


            self._consume('DELIMITER', '}')
            if_stmt['false_block'] = false_block

        self.ast.append(if_stmt)

    def loop(self):
        # Parses a loop statement
        self._consume('DIG')
        self._consume('DELIMITER', '(')
        condition = self.condition()
        self._consume('DELIMITER', ')')
        self._consume('DELIMITER', '{')
        
        
        ast_before = len(self.ast)
        self.program()
        body = self.ast[ast_before:]
        self.ast = self.ast[:ast_before]
        
        self._consume('DELIMITER', '}')
        
        self.ast.append({
            'type': 'while_statement',
            'condition': condition,
            'body': body
        })

    def expression(self):
        # Parse left-hand side
        node = self.term()
        
        # Handle binary operations (e.g., 64 + 1)
        while self._match('OPERATOR'):
            op = self.current_token['value']
            self._advance()
            right = self.term()
            node = {'type': 'binary_op', 'left': node, 'op': op, 'right': right}
        
        return node
        
    def term(self):
        # Handle literals, identifiers, and parentheses
        if self._match('LITERAL'):
            token = self.current_token
            self._advance()
            return {'type': 'literal', 'value': token['value']}
        elif self._match('IDENTIFIER'):
            token = self.current_token
            self._advance()
            return {'type': 'identifier', 'name': token['value']}
        elif self._match('DELIMITER', '('):
            self._advance()
            expr = self.expression()
            self._consume('DELIMITER', ')', "Missing closing parenthesis")
            return expr
        else:
            raise self._error("Expected expression")

    def condition(self):
        # conditions parser
        left = self.expression()
        if self._match('OPERATOR'):
            op = self.current_token['value']
            self._advance()
            right = self.expression()
            return {'type': 'binary_op', 'left': left, 'op': op, 'right': right}
        return left

    def _at_end(self):
        # checks if the process has reached the end of the token list
        return self.pos >= len(self.tokens)

    def _match(self, kind, value=None):
        # checks if the current token is of the expected kind
        if self._at_end():
            return False
        if self.current_token['kind'] != kind:
            return False
        if value is not None and self.current_token['value'] != value:
            return False
        return True

    def _advance(self):
        # proceed to the next token
        token = self.current_token
        self.pos += 1
        self.current_token = self.tokens[self.pos] if self.pos < len(self.tokens) else None
        return token

    def _consume(self, kind, value=None, message="Unexpected token"):
        #error handling in the event that an expected token does not match the expected kind
        
        if self._match(kind, value):
            return self._advance() # Move to the next token
        else:
            # Raise an error if the current token is not of the expected kind
            expected_str = f"'{kind}'"
            if value is not None:
                expected_str += f" with value '{value}'"
            raise self._error(f"{message}. Expected {expected_str}")

    def _error(self, message):
        # this creates the syntax error format expected attaching the line and code snippet associated with the error
        
        token = self.current_token
        code_snippet = f"Line {token['line']}: {token['value']}"
        return SyntaxError(message, line=token['line'], code_snippet=code_snippet)